version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./travelForum
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 travelForum.wsgi:application
    volumes:
      - ./travelForum:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  frontend:
    build:
      context: ./travelForum/travel-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./travelForum/staticfiles:/app/staticfiles
      - ./travelForum/travel-frontend/build:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend

volumes:
  mysql_data: