# Dockerfile.frontend
FROM node:18

WORKDIR /app/travel-frontend

# Copy package.json and package-lock.json to install dependencies
COPY travel-frontend/package*.json ./
RUN npm install

# Copy the rest of the React app's source code
COPY travel-frontend/ ./

# Expose port 3000 (the default port for React dev server)
EXPOSE 3000

# Command to run the React app
CMD ["npm", "start"]
