# Dockerfile.backend
FROM python:3.12

WORKDIR /app

# Copy Django project files
COPY . /app

# Install Django dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Collect static files (if needed)
RUN python manage.py collectstatic --noinput

# Expose the port for Gunicorn
EXPOSE 8000

# Command to run Django app using Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "travelForum.wsgi:application"]