services:
  frontend:
    build:
      context: ./travel-frontend  # Specify the context directory for the frontend
    image: tautvis520/frontend:latest
    ports:
      - "3000:3000"  # Map port 3000 for React frontend
    environment:
      - CHOKIDAR_USEPOLLING=true  # Useful for live reloading in Docker
    working_dir: /app/travel-frontend
    command: ["npm", "start"]  # Starts the React development server

  backend:
    build:
      context: ./travel-backend  # Specify the context directory for the backend
    image: tautvis520/backend:latest
    ports:
      - "8000:8000"  # Map port 8000 for Django backend
    volumes:
      - .:/app
    depends_on:
      - db  # Add dependency on the db (MySQL) service
    environment:
      - DB_HOST=db  # Use the correct service name for MySQL
      - DB_NAME=travelhub_database
      - DB_USER=traveler
      - DB_PASSWORD=traveler

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: traveler
      MYSQL_DATABASE: travelhub_database
      MYSQL_USER: traveler
      MYSQL_PASSWORD: traveler
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: